/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedKarriererIndexRouteImport } from './routes/_authenticated/karrierer.index'
import { Route as AuthenticatedKarriererIdRouteImport } from './routes/_authenticated/karrierer.$id'
import { Route as AuthenticatedKarriererIdIndexRouteImport } from './routes/_authenticated/karrierer.$id.index'
import { Route as AuthenticatedKarriererIdImportRouteImport } from './routes/_authenticated/karrierer.$id.import'
import { Route as AuthenticatedKarriererIdTrupRouteImport } from './routes/_authenticated/karrierer.$id.trup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedKarriererIndexRoute =
  AuthenticatedKarriererIndexRouteImport.update({
    id: '/karrierer/',
    path: '/karrierer/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKarriererIdRoute =
  AuthenticatedKarriererIdRouteImport.update({
    id: '/karrierer/$id',
    path: '/karrierer/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKarriererIdIndexRoute =
  AuthenticatedKarriererIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedKarriererIdRoute,
  } as any)
const AuthenticatedKarriererIdImportRoute =
  AuthenticatedKarriererIdImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedKarriererIdRoute,
  } as any)
const AuthenticatedKarriererIdTrupRoute =
  AuthenticatedKarriererIdTrupRouteImport.update({
    id: '/trup',
    path: '/trup',
    getParentRoute: () => AuthenticatedKarriererIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/karrierer/$id': typeof AuthenticatedKarriererIdRouteWithChildren
  '/karrierer/': typeof AuthenticatedKarriererIndexRoute
  '/karrierer/$id/import': typeof AuthenticatedKarriererIdImportRoute
  '/karrierer/$id/trup': typeof AuthenticatedKarriererIdTrupRoute
  '/karrierer/$id/': typeof AuthenticatedKarriererIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/karrierer': typeof AuthenticatedKarriererIndexRoute
  '/karrierer/$id/import': typeof AuthenticatedKarriererIdImportRoute
  '/karrierer/$id/trup': typeof AuthenticatedKarriererIdTrupRoute
  '/karrierer/$id': typeof AuthenticatedKarriererIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/karrierer/$id': typeof AuthenticatedKarriererIdRouteWithChildren
  '/_authenticated/karrierer/': typeof AuthenticatedKarriererIndexRoute
  '/_authenticated/karrierer/$id/import': typeof AuthenticatedKarriererIdImportRoute
  '/_authenticated/karrierer/$id/trup': typeof AuthenticatedKarriererIdTrupRoute
  '/_authenticated/karrierer/$id/': typeof AuthenticatedKarriererIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/karrierer/$id'
    | '/karrierer/'
    | '/karrierer/$id/import'
    | '/karrierer/$id/trup'
    | '/karrierer/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/karrierer'
    | '/karrierer/$id/import'
    | '/karrierer/$id/trup'
    | '/karrierer/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/karrierer/$id'
    | '/_authenticated/karrierer/'
    | '/_authenticated/karrierer/$id/import'
    | '/_authenticated/karrierer/$id/trup'
    | '/_authenticated/karrierer/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/karrierer/': {
      id: '/_authenticated/karrierer/'
      path: '/karrierer'
      fullPath: '/karrierer/'
      preLoaderRoute: typeof AuthenticatedKarriererIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/karrierer/$id': {
      id: '/_authenticated/karrierer/$id'
      path: '/karrierer/$id'
      fullPath: '/karrierer/$id'
      preLoaderRoute: typeof AuthenticatedKarriererIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/karrierer/$id/': {
      id: '/_authenticated/karrierer/$id/'
      path: '/'
      fullPath: '/karrierer/$id/'
      preLoaderRoute: typeof AuthenticatedKarriererIdIndexRouteImport
      parentRoute: typeof AuthenticatedKarriererIdRoute
    }
    '/_authenticated/karrierer/$id/import': {
      id: '/_authenticated/karrierer/$id/import'
      path: '/import'
      fullPath: '/karrierer/$id/import'
      preLoaderRoute: typeof AuthenticatedKarriererIdImportRouteImport
      parentRoute: typeof AuthenticatedKarriererIdRoute
    }
    '/_authenticated/karrierer/$id/trup': {
      id: '/_authenticated/karrierer/$id/trup'
      path: '/trup'
      fullPath: '/karrierer/$id/trup'
      preLoaderRoute: typeof AuthenticatedKarriererIdTrupRouteImport
      parentRoute: typeof AuthenticatedKarriererIdRoute
    }
  }
}

interface AuthenticatedKarriererIdRouteChildren {
  AuthenticatedKarriererIdImportRoute: typeof AuthenticatedKarriererIdImportRoute
  AuthenticatedKarriererIdTrupRoute: typeof AuthenticatedKarriererIdTrupRoute
  AuthenticatedKarriererIdIndexRoute: typeof AuthenticatedKarriererIdIndexRoute
}

const AuthenticatedKarriererIdRouteChildren: AuthenticatedKarriererIdRouteChildren =
  {
    AuthenticatedKarriererIdImportRoute: AuthenticatedKarriererIdImportRoute,
    AuthenticatedKarriererIdTrupRoute: AuthenticatedKarriererIdTrupRoute,
    AuthenticatedKarriererIdIndexRoute: AuthenticatedKarriererIdIndexRoute,
  }

const AuthenticatedKarriererIdRouteWithChildren =
  AuthenticatedKarriererIdRoute._addFileChildren(
    AuthenticatedKarriererIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedKarriererIdRoute: typeof AuthenticatedKarriererIdRouteWithChildren
  AuthenticatedKarriererIndexRoute: typeof AuthenticatedKarriererIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedKarriererIdRoute: AuthenticatedKarriererIdRouteWithChildren,
  AuthenticatedKarriererIndexRoute: AuthenticatedKarriererIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
