/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedKarriererIndexRouteImport } from './routes/_authenticated/karrierer.index'
import { Route as AuthenticatedKarriererIdRouteImport } from './routes/_authenticated/karrierer.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedKarriererIndexRoute =
  AuthenticatedKarriererIndexRouteImport.update({
    id: '/karrierer/',
    path: '/karrierer/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKarriererIdRoute =
  AuthenticatedKarriererIdRouteImport.update({
    id: '/karrierer/$id',
    path: '/karrierer/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/karrierer/$id': typeof AuthenticatedKarriererIdRoute
  '/karrierer/': typeof AuthenticatedKarriererIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/karrierer/$id': typeof AuthenticatedKarriererIdRoute
  '/karrierer': typeof AuthenticatedKarriererIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/karrierer/$id': typeof AuthenticatedKarriererIdRoute
  '/_authenticated/karrierer/': typeof AuthenticatedKarriererIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/karrierer/$id' | '/karrierer/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/karrierer/$id' | '/karrierer'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/karrierer/$id'
    | '/_authenticated/karrierer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/karrierer/': {
      id: '/_authenticated/karrierer/'
      path: '/karrierer'
      fullPath: '/karrierer/'
      preLoaderRoute: typeof AuthenticatedKarriererIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/karrierer/$id': {
      id: '/_authenticated/karrierer/$id'
      path: '/karrierer/$id'
      fullPath: '/karrierer/$id'
      preLoaderRoute: typeof AuthenticatedKarriererIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedKarriererIdRoute: typeof AuthenticatedKarriererIdRoute
  AuthenticatedKarriererIndexRoute: typeof AuthenticatedKarriererIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedKarriererIdRoute: AuthenticatedKarriererIdRoute,
  AuthenticatedKarriererIndexRoute: AuthenticatedKarriererIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
